# Generated by Django 3.0.3 on 2020-03-12 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_payment',
            new_name='payment_due',
        ),
    ]
