# Generated by Django 3.0.3 on 2020-03-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='level',
            field=models.CharField(choices=[('1', 'Beginner'), ('2', 'Novice'), ('3', 'Intermediate'), ('4', 'Advanced'), ('5', 'Expert')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='lessons',
            field=models.ManyToManyField(to='classes.Lesson'),
        ),
    ]
