# Generated by Django 3.0.3 on 2020-03-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200305_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='class_topics/')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='duration',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='topics',
            field=models.ManyToManyField(to='classes.Topic'),
        ),
    ]
